### ISSUE TITLE
Worst Vue.js component I have ever come across.

### ISSUE THREAD

**Issue by fgutteridge** [alexiscolin/vue-timeselector#6]
Completely unusable. Illogical throughout (why would anyone want the default time to be 1:00 AM? Are you fucking stupid? Why does your 'placeholder' prop not actually create a placeholder?

Clearly you are new to development, so I advise that you stay far from it. It's not for you.

**Comment by alexiscolin** [comment]
Thank you for your feedback dumbass.

First of all, you are on Github, let me teach you that's a place where people share some code to the community even if it's not perfect. Do you know why ? Because you can help people by sharing them your "big" knowledge. Because you seem to be a "great" developer, why not making a pull request ? No... you prefer to insult people like the dumbass you are...

But you know what, you don't need to do a pull request, you should learn to read first...

1) The default time is 00:00 AM (depends on UTC props). But anyone (except you, illiterate dumbass...) can display the default value as he wish. Just have to complete the `v-model` with the date you want. It will become a default date value... So clever people fill it with their own value ;)

2) Placeholder prop definitely creates a placeholder that disappears when you select a date... 

Must learn to be lowly and polite, I'm not your friend and I don't care about your opinion about me. BTW, development is all about sharing, you will learn that...
